### PR TITLE
Factories may return NULL

### PR DESCRIPTION
**Pull request by dragosprotung**

### CODE REVIEW

**Comment by xabbuh** [comment]
Thank you for this PR. Can we also add a test that will cover a use case which would break without this?

**Comment by dragosprotung** [comment]
Done

**Comment by xabbuh** [comment]
Thanks for the additional test. 👍 What I wonder though is whether it actually makes sense for a factory to return `null` or if that isn't a case where we should throw an exception (and maybe catch and transform it into an error afterwards). 🤔 Do you have a real world use case where returning `null` is the expected behaviour?

**Comment by dragosprotung** [comment]
Yes, i think it does makes sense. I do have many cases where the factory returns `null`. Most common scenario is when I have a collection type of object that can hold 1 or more elements. In that case i want to have it as `null` if there are no elements to store in the collection object

**Comment by xabbuh** [comment]
A last question for clarification: This does work with the 0.2.0 release, but breaks on the latest `main` branch?

**Comment by dragosprotung** [comment]
Returning `null` in the factory works on `0.2.0` as there is no strong types and it stopped working since #119

**Pull request merged**
